import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
          dark: "hsl(var(--primary-dark))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        cacador: {
          pink: "hsl(var(--cacador-pink))",
          "pink-light": "hsl(var(--cacador-pink-light))",
          yellow: "hsl(var(--cacador-yellow))",
          "bg-main": "hsl(var(--cacador-bg-main))",
          "bg-alt": "hsl(var(--cacador-bg-alt))",
          "bg-section": "hsl(var(--cacador-bg-section))",
          "dark-card": "hsl(var(--cacador-dark-card))",
          "text-primary": "hsl(var(--cacador-text-primary))",
          "text-secondary": "hsl(var(--cacador-text-secondary))",
        },
        elite: {
          black: "hsl(var(--elite-black))",
          white: "hsl(var(--elite-white))",
          gold: "hsl(var(--elite-gold))",
          "gold-light": "hsl(var(--elite-gold-light))",
          "gold-dark": "hsl(var(--elite-gold-dark))",
          gray: "hsl(var(--elite-gray))",
        },
        ice: {
          "bg-main": "hsl(var(--ice-bg-main))",
          "bg-card": "hsl(var(--ice-bg-card))",
          "bg-card-alt": "hsl(var(--ice-bg-card-alt))",
          "blue-primary": "hsl(var(--ice-blue-primary))",
          "blue-secondary": "hsl(var(--ice-blue-secondary))",
          "cyan": "hsl(var(--ice-cyan))",
          "purple": "hsl(var(--ice-purple))",
          "text-primary": "hsl(var(--ice-text-primary))",
          "text-secondary": "hsl(var(--ice-text-secondary))",
          "border": "hsl(var(--ice-border))",
        },
        clube: {
          black: "hsl(var(--clube-black))",
          "black-alt": "hsl(var(--clube-black-alt))",
          "red-primary": "hsl(var(--clube-red-primary))",
          "red-dark": "hsl(var(--clube-red-dark))",
          gray: "hsl(var(--clube-gray))",
          white: "hsl(var(--clube-white))",
          "input-bg": "hsl(var(--clube-input-bg))",
          border: "hsl(var(--clube-border))",
        },
        "dark-gradient": {
          from: "hsl(var(--dark-gradient-from))",
          to: "hsl(var(--dark-gradient-to))",
        },
        "card-dark": {
          DEFAULT: "hsl(var(--card-dark))",
          foreground: "hsl(var(--card-dark-foreground))",
        },
        badge: {
          success: "hsl(var(--badge-success))",
          "success-foreground": "hsl(var(--badge-success-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-card': 'var(--gradient-card)',
        'gradient-subtle': 'var(--gradient-subtle)',
        'gradient-yellow': 'var(--gradient-yellow)',
        "gradient-soudrop": "var(--gradient-soudrop)",
        "gradient-shopee": "var(--gradient-shopee)",
        "gradient-links-background": "var(--gradient-links-background)",
        "gradient-cacador-hero": "var(--gradient-cacador-hero)",
        "gradient-cacador-pink": "var(--gradient-cacador-pink)",
        "gradient-cacador-cta": "var(--gradient-cacador-cta)",
        "gradient-elite-gold": "var(--gradient-elite-gold)",
        "gradient-elite-bg": "var(--gradient-elite-bg)",
        "gradient-ice-hero": "var(--gradient-ice-hero)",
        "gradient-ice-primary": "var(--gradient-ice-primary)",
        "gradient-ice-card": "var(--gradient-ice-card)",
        "gradient-ice-subtle": "var(--gradient-ice-subtle)",
        "gradient-clube-hero": "var(--gradient-clube-hero)",
        "gradient-clube-red": "var(--gradient-clube-red)",
        "gradient-clube-card": "var(--gradient-clube-card)",
      },
      boxShadow: {
        'glow': 'var(--shadow-glow)',
        'yellow-glow': 'var(--shadow-yellow-glow)',
        'card': 'var(--shadow-card)',
        'elegant': 'var(--shadow-elegant)',
        'cacador-pink': 'var(--shadow-cacador-pink)',
        'cacador-yellow': 'var(--shadow-cacador-yellow)',
        'cacador-cta': 'var(--shadow-cacador-cta)',
        'elite-gold': 'var(--shadow-elite-gold)',
        'elite-gold-strong': 'var(--shadow-elite-gold-strong)',
        'ice-glow': 'var(--shadow-ice-glow)',
        'ice-cyan': 'var(--shadow-ice-cyan)',
        'ice-purple': 'var(--shadow-ice-purple)',
        'clube-red': 'var(--shadow-clube-red)',
        'clube-red-strong': 'var(--shadow-clube-red-strong)',
      },
      fontFamily: {
        'sans': ['Montserrat', 'Inter', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "pulse": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.5" } },
        "slide-up": { "0%": { opacity: "0", transform: "translateY(30px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-down": { "0%": { opacity: "0", transform: "translateY(-30px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-left": { "0%": { opacity: "0", transform: "translateX(30px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "slide-right": { "0%": { opacity: "0", transform: "translateX(-30px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "zoom-in": { "0%": { opacity: "0", transform: "scale(0.8)" }, "100%": { opacity: "1", transform: "scale(1)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out",
        "pulse": "pulse 3s ease-in-out infinite",
        "slide-up": "slide-up 0.6s ease-out",
        "slide-down": "slide-down 0.6s ease-out",
        "slide-left": "slide-left 0.6s ease-out",
        "slide-right": "slide-right 0.6s ease-out",
        "zoom-in": "zoom-in 0.6s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;